### ISSUE TITLE
loading trained model

### ISSUE THREAD

**Issue by furkaya96** [ForawardStar/EDIT#4]
Hello, your work is very successful. Thank you for your efforts.
I had a little trouble loading the trained model. So after examining the code a bit, I realized that you save the entire model instead of `model.state_dict()` while saving your model. So we need to load a model by `model = torch.load (model_path)`.

**Comment by ForawardStar** [comment]
> 
> 
> Hello, your work is very successful. Thank you for your efforts.
> I had a little trouble loading the trained model. So after examining the code a bit, I realized that you save the entire model instead of `model.state_dict()` while saving your model. So we need to load a model by `model = torch.load (model_path)`.

Thank you very much! It is a mistake in our code, now we have correctted it.
